server:
  port: 8280
  servlet:
    context-path: /system

spring:
  application:
    name: system-api

  cloud:
    nacos:
      discovery:
        server-addr: nacos

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/online_hospital_system?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: 123456

aliyun:
  oss:
    access-key-id:
    access-key-secret:
    endpoint:
    bucket-name:
