server:
  port: 8230
  servlet:
    context-path: /registration

spring:
  application:
    name: registration-api

  cloud:
    nacos:
      discovery:
        server-addr: nacos

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/online_hospital_registration?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
